/**
 * MetaWall_achievement API DOC
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                      from 'rxjs';

import { commentsViewModel, PostViewModel, sendCommentSearchModel, UserSignUpViewModel } from '../model/models';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class Posts_Service {

    protected basePath = 'https://damp-plateau-24758.herokuapp.com';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     *
     *   刪除單筆貼文留言  &lt;ul&gt;  &lt;li&gt;取得 Token 至上方 Authorize 按鈕以格式 &lt;code&gt;Bearer ＜Token＞&lt;/code&gt; 加入設定，swagger 文件中鎖頭上鎖表示登入，可使用登入權限。&lt;/li&gt;  &lt;/ul&gt;
     * @param id   &lt;ul&gt;  &lt;li&gt;取得特定使用者的所有貼文，關連留言訊息資料格式。&lt;/li&gt;  &lt;li&gt;Params Path Variables &lt;code&gt;:id&lt;/code&gt; (comment ID)&lt;/li&gt;  &lt;/ul&gt;
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public postsCommentIdDelete(id: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public postsCommentIdDelete(id: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public postsCommentIdDelete(id: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public postsCommentIdDelete(id: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling postsCommentIdDelete.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});

        let headers = this.defaultHeaders;

        // authentication (apiKeyAuth) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            queryParameters = queryParameters.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.delete<any>(`${this.basePath}/posts/comment/${encodeURIComponent(String(id))}`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     *
     * 刪除所有貼文
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public postsDelete(observe?: 'body', reportProgress?: boolean): Observable<any>;
    public postsDelete(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public postsDelete(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public postsDelete(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});

        let headers = this.defaultHeaders;

        // authentication (apiKeyAuth) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            queryParameters = queryParameters.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.delete<any>(`${this.basePath}/posts/`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     *
     *   &lt;p&gt;取得所有貼文。&lt;/p&gt;  參數用法：  &lt;ul&gt;  &lt;li&gt;取得 Token 至上方 Authorize 按鈕以格式 &lt;code&gt;Bearer ＜Token＞&lt;/code&gt; 加入設定，swagger 文件中鎖頭上鎖表示登入，可使用登入權限。&lt;/li&gt;  &lt;li&gt;&lt;code&gt;postsLength&lt;/code&gt; 在相關網址參數運算下，執行後回傳資料長度。&lt;/li&gt;  &lt;/ul&gt;
     * @param timeSort   &lt;code&gt;timeSort&lt;/code&gt; 參數：  &lt;ul&gt;  &lt;li&gt;預設新到舊&lt;/li&gt;  &lt;li&gt;是否有 &lt;code&gt;asc&lt;/code&gt; 值？，有值有舊到新；沒值有新到舊。&lt;/li&gt;  &lt;/ul&gt;
     * @param q   &lt;code&gt;q&lt;/code&gt; 參數：  &lt;ul&gt;  &lt;li&gt;查找物件中的留言 &lt;code&gt;discussContent&lt;/code&gt;。&lt;/li&gt;  &lt;li&gt;用正則表達式以 JS 轉 mongDB 語法 &lt;code&gt;.find( parName: /&lt;查尋字串&gt;/)&lt;/code&gt;。&lt;/li&gt;  &lt;/ul&gt;
     * @param pageNum   &lt;code&gt;pageNum&lt;/code&gt; 參數：取頁面資料筆數長度 (目前分頁數 &lt;code&gt;0&lt;/code&gt; 為第一頁)  &lt;ul&gt;  &lt;li&gt;判斷網址參數 &lt;code&gt;pageSize&lt;/code&gt; 是否有值，若無值會段 &lt;code&gt;0&lt;/code&gt; 取出所有資料。&lt;/li&gt;  &lt;li&gt;參數以 &lt;code&gt;1&lt;/code&gt; 累計。&lt;/li&gt;  &lt;/ul&gt;
     * @param pageSize   &lt;code&gt;pageSize&lt;/code&gt; 參數：取頁面資料區間 (分頁中每頁的資料筆數)  &lt;ul&gt;  &lt;li&gt;由第 &lt;code&gt;0&lt;/code&gt; 筆數位置做為 &lt;code&gt;1&lt;/code&gt; 開始計算。&lt;/li&gt;  &lt;li&gt;參數以由 &lt;code&gt;1&lt;/code&gt; 以累計。&lt;/li&gt;  &lt;li&gt;網址參數 &lt;code&gt;pageSize * pageNum &#x3D; 頁面數&lt;/code&gt; 做為計算結果。&lt;/li&gt;  &lt;/ul&gt;
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public postsGet(timeSort?: string, q?: string, pageNum?: string, pageSize?: string, observe?: 'body', reportProgress?: boolean): Observable<PostViewModel>;
    public postsGet(timeSort?: string, q?: string, pageNum?: string, pageSize?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<PostViewModel>>;
    public postsGet(timeSort?: string, q?: string, pageNum?: string, pageSize?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<PostViewModel>>;
    public postsGet(timeSort?: string, q?: string, pageNum?: string, pageSize?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {





        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (timeSort !== undefined && timeSort !== null) {
            queryParameters = queryParameters.set('timeSort', <any>timeSort);
        }
        if (q !== undefined && q !== null) {
            queryParameters = queryParameters.set('q', <any>q);
        }
        if (pageNum !== undefined && pageNum !== null) {
            queryParameters = queryParameters.set('pageNum', <any>pageNum);
        }
        if (pageSize !== undefined && pageSize !== null) {
            queryParameters = queryParameters.set('pageSize', <any>pageSize);
        }

        let headers = this.defaultHeaders;

        // authentication (apiKeyAuth) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            queryParameters = queryParameters.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<any>(`${this.basePath}/posts/`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     *
     *   新增貼文留言功能  &lt;ul&gt;  &lt;li&gt;取得 Token 至上方 Authorize 按鈕以格式 &lt;code&gt;Bearer ＜Token＞&lt;/code&gt; 加入設定，swagger 文件中鎖頭上鎖表示登入，可使用登入權限。&lt;/li&gt;  &lt;li&gt;Heders Token 指定留言 user (&lt;code&gt;commentUser&lt;/code&gt;)。&lt;/li&gt;  &lt;li&gt;網址路由 &lt;code&gt;:id&lt;/code&gt; 傳入 post id 在特定貼文中留言。&lt;/li&gt;  &lt;li&gt;成功留言將資料寫入 &lt;code&gt;Comment&lt;/code&gt; collection 中建出 document。&lt;/li&gt;  &lt;/ul&gt;
     * @param id Params path Variables &lt;code&gt;:id&lt;/code&gt; (posts ID)
     * @param body Body 資料格式
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public postsIdCommentPost(id: string, body: sendCommentSearchModel, observe?: 'body', reportProgress?: boolean): Observable<commentsViewModel>;
    public postsIdCommentPost(id: string, body: sendCommentSearchModel, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<commentsViewModel>>;
    public postsIdCommentPost(id: string, body: sendCommentSearchModel, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<commentsViewModel>>;
    public postsIdCommentPost(id: string, body: sendCommentSearchModel, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling postsIdCommentPost.');
        }

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling postsIdCommentPost.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});

        let headers = this.defaultHeaders;

        // authentication (apiKeyAuth) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            queryParameters = queryParameters.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<any>(`${this.basePath}/posts/${encodeURIComponent(String(id))}/comment`,
            body,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     *
     *   刪除單筆貼文  &lt;ul&gt;  &lt;li&gt;取得 Token 至上方 Authorize 按鈕以格式 &lt;code&gt;Bearer ＜Token＞&lt;/code&gt; 加入設定，swagger 文件中鎖頭上鎖表示登入，可使用登入權限。&lt;/li&gt;  &lt;li&gt;網址路由以 &lt;code&gt;:id&lt;/code&gt; 傳入參數，直接針對 Posts 中的 document id 進行刪除。&lt;/li&gt;  &lt;/ul&gt;
     * @param id
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public postsIdDelete(id: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public postsIdDelete(id: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public postsIdDelete(id: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public postsIdDelete(id: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling postsIdDelete.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});

        let headers = this.defaultHeaders;

        // authentication (apiKeyAuth) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            queryParameters = queryParameters.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.delete<any>(`${this.basePath}/posts/${encodeURIComponent(String(id))}`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     *
     *   更新單筆貼文  &lt;ul&gt;  &lt;li&gt;取得 Token 至上方 Authorize 按鈕以格式 &lt;code&gt;Bearer ＜Token＞&lt;/code&gt; 加入設定，swagger 文件中鎖頭上鎖表示登入，可使用登入權限。&lt;/li&gt;  &lt;/ul&gt;
     * @param id
     * @param body Body 資料格式
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public postsIdPatch(id: string, body: UserSignUpViewModel, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public postsIdPatch(id: string, body: UserSignUpViewModel, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public postsIdPatch(id: string, body: UserSignUpViewModel, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public postsIdPatch(id: string, body: UserSignUpViewModel, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling postsIdPatch.');
        }

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling postsIdPatch.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});

        let headers = this.defaultHeaders;

        // authentication (apiKeyAuth) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            queryParameters = queryParameters.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.patch<any>(`${this.basePath}/posts/${encodeURIComponent(String(id))}`,
            body,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     *
     *   新增單筆貼文  &lt;ul&gt;  &lt;li&gt;取得 Token 至上方 Authorize 按鈕以格式 &lt;code&gt;Bearer ＜Token＞&lt;/code&gt; 加入設定，swagger 文件中鎖頭上鎖表示登入，可使用登入權限。&lt;/li&gt;  &lt;li&gt;新增貼文需先有 user.id 登入取得 Tokne&lt;/li&gt;  &lt;li&gt;資料格式查看必填欄位，點按下方 Model 切換後，屬性欄位名稱的後方紅色的 &lt;code&gt;*&lt;/code&gt;&lt;/li&gt;  &lt;li&gt;透過 user.id 向 posts 的屬性欄位 &lt;code&gt;userData&lt;/code&gt; 關連。&lt;/li&gt;  &lt;/ul&gt;
     * @param body
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public postsPost(body: any, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public postsPost(body: any, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public postsPost(body: any, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public postsPost(body: any, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling postsPost.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});

        let headers = this.defaultHeaders;

        // authentication (apiKeyAuth) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            queryParameters = queryParameters.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<any>(`${this.basePath}/posts/`,
            body,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     *
     *   取得特定使用者的所有貼文，關連留言訊息。  &lt;ul&gt;  &lt;li&gt;不帶 Token 在可對外查看。&lt;/li&gt;  &lt;/ul&gt;
     * @param id   &lt;ul&gt;  &lt;li&gt;取得特定使用者的所有貼文，關連留言訊息資料格式。&lt;/li&gt;  &lt;li&gt;Params Path Variables &lt;code&gt;:id&lt;/code&gt; (user ID)&lt;/li&gt;  &lt;/ul&gt;
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public postsUserIdGet(id: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public postsUserIdGet(id: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public postsUserIdGet(id: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public postsUserIdGet(id: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling postsUserIdGet.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<any>(`${this.basePath}/posts/user/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
